### ISSUE TITLE
Save bazel flags proto to disk so that we can read it directly instead of invoking bazel

### ISSUE THREAD

**Issue by JesseTatasciore** [aspect-build/aspect-cli#139]
After the first run of an aspect command where we want to be able to pass through bazel flags, we should save the flags we requested to the disk so that they can be accessed the next time the same command is run with the same bazel version. This should hopefully work out to be quicker than querying bazel each time

**Comment by alexeagle** [comment]
We discussed this and determined it's not worth it. `bazel help flags-as-proto` just spawns a c++ subprocess which spits out the data directly from the binary, without querying anything. It's perfectly fast as a source of the string data, and avoids the complexity of managing cache invalidation if we were to copy it.

**Comment by mattem** [comment]
flags-as-proto launches the bazel sever, not just the client.
