### ISSUE TITLE
Incompatibility with `bazel` for `info bazel-bin --color=no`

### ISSUE THREAD

**Issue by irfansharif** [aspect-build/aspect-cli#203]
Was playing around with `aspect` and noticed that `aspect info bazel-bin --color=no` errors out while the corresponding `bazel` invocation doesn't.

**Comment by f0rmiga** [comment]
@irfansharif thanks for reporting this bug. We fixed it in #204 and it went into the [v0.5.0](https://github.com/aspect-build/aspect-cli/releases/tag/v0.5.0) release.
