### ISSUE TITLE
Support building from source outside of a git repository

### ISSUE THREAD

**Issue by cgrindel** [aspect-build/aspect-cli#304]
Related to aspect-build/silo#329.

## Why?
Homebrew build from source (`brew reinstall --build-from-source --verbose --debug aspect-cli`)

## Consierations
The `buildinfo/bazel_stamp_info.sh` should check if there is a git repository.
- If so, do what it does today
- If no, check for `ASPECT_VERSION` env variable. (Homebrew formula will set this value prior to the build.)

**Comment by alexeagle** [comment]
This sounds wrong to me, the user will not have access to our source code. If we are on our own tap then we can install a downloaded binary right?

**Comment by cgrindel** [comment]
This is my understanding.
- The Aspect CLI is open-source. 
- The Homebrew formula pattern is to provide the `install` stanza that builds from source.
  - If we were going to push to be in Homebrew core, they would want this pattern so that they can build the bottles.
  - Since we will host our tap, we will build our bottles.
- This issue merely allows us/someone to build the code specifying the semver instead of using the git tricks to figure it out.
  - Bazelisk does by [passing some flags to `go build`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazelisk.rb#L29).
  - I think Bazel is doing it by [setting an environment variable](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb#L31).

**Comment by alexeagle** [comment]
I think when/if we want a homebrew formula (call it aspect-oss for clarity) that does want to build the tool from sources in this repo, it should be just like the bazelisk homebrew formula, which is to say, it would use the `go` tool to build the program and not bother with Bazel at all. So then this could be closed as WAI?
