### ISSUE TITLE
[Bug]: outputs && configure verbs don't accept common flags

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#365]
### What happened?

```
$ bazel outputs --invocation_id=5f51c87f-ac69-49a2-a800-e3969abffd90 -- "attr("tags", "\bdeliverable\b", //...)" ExecutableHash
Error: unknown flag: --invocation_id

$ bazel configure --config=workflows
Error: unknown flag: --config
```

### Version

5.0.3

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
I have a fix for the `outputs` verb since it should accept all flags the `aquery` accepts. Seems to be that `configure` should not accept any common bazel flags since its not calling bazel under the hood.
