### ISSUE TITLE
[FR]: Add progress bar

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/aspect-cli#386]
I saw this old [PR](https://github.com/bazelbuild/bazelisk/pull/5) from Bazelisk. Would be a nice easy addition to add to our CLI to improve DX when downloading Bazel, plugins, etc...

**Comment by alexeagle** [comment]
Bonus points if we have a progress bar for the whole invocation.

@evmar showed me a cool prototype he was working on for Ninja...

**Comment by alexeagle** [comment]
I think we should close this and just plan on a rewrite using https://github.com/facebookincubator/superconsole
