### ISSUE TITLE
[FR]: Generate multiple `ts_project()` targets with Gazelle extension

### ISSUE THREAD

**Issue by dgp1130** [aspect-build/aspect-cli#427]
### What is the current behavior?

The Gazelle JS extension currently only generates up to two `ts_project()` targets, one for production code and another for test code. This is limiting since many projects may want to have multiple `ts_project()` files based on a naming convention, yet as it is today, Gazelle will always put source files into these two `ts_project()` targets, which is quite limiting.

### Describe the feature

Ideally, we would have a Gazelle directive which maps a filename glob to a target name. This would allow file naming conventions to inform the `BUILD` structure generated.

In my particular case, I have two sets of TypeScript files with the naming convention `*.prerender.ts` and `*.client.ts`. These need to be built in distinct `ts_project()` targets with distinct dependencies because one targets the Node runtime while the other targets a browser runtime. All the `*.prerender.ts` files should go under a `:prerender` target, while the `*.client.ts` files should go under a `:client` target.

In a conversation with @jbedard, they suggested an approach like:

```python
# gazelle:js_custom_target_files prerender *.prerender.ts
# gazelle:js_custom_target_files scripts *.client.ts
```

This should be enough information for Gazelle to generate and multiple `ts_project()` targets with a reasonable structure.

**Comment by valerybugakov** [comment]
At Sourcegraph, we're also looking forward to this improvement.
