### ISSUE TITLE
releases don't appear as "clean"

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#47]
install latest GH release, then

% aspect version
Aspect version: v0.0.6 (with local changes)

I fought with this for a couple hours but didn't figure it out. Something about the GH actions environment.

**Comment by f0rmiga** [comment]
I'll take this.

**Comment by alexeagle** [comment]
It's super-mystery, I cut several releases in a row using the GH actions with a bunch of extra git commands added, and I don't see how we are failing to determine that the workspace status is pristine.
You could make a fork of this project to experiment on, since I think you'll have to run the real release action. Maybe possible to make it do a dry-run for a PR branch though.

**Comment by f0rmiga** [comment]
Fixed in https://github.com/aspect-build/aspect-cli/pull/76.

**Comment by f0rmiga** [comment]
Triggered a release for this in https://github.com/aspect-build/aspect-cli/runs/4292830969 (v0.1.1).
