### ISSUE TITLE
[FR]: consider forwarding flags unrecognized by bazel-lint down to bazel-build 

### ISSUE THREAD

**Issue by plobsing** [aspect-build/aspect-cli#557]
### What is the current behavior?

At the moment, flags to `bazel build` are accepted only when offset by a `--`.

Doesn't work:

```
❯ bazel lint --java_runtime_version=remotejdk_11  src:all
Error: unknown flag: --java_runtime_version
```

Workaround:

```
 bazel lint -- --java_runtime_version=remotejdk_11 src:all 
```

### Describe the feature

Having to delimit the flags feels like a bit of a leaky abstraction - as a user, I am forced to understand that the `lint` subcommand isn't like the others and is implemented as a wrapper over `build`. It'd be nice if users didn't have to know this. Maybe `bazel lint` could forward flags it doesn't recognize on to `bazel build`?

**Comment by alexeagle** [comment]
I think @gregmagolan fixed this in https://github.com/aspect-build/aspect-cli/commit/a20621d393cc1c0c37c154883809d19e629bdece
