### ISSUE TITLE
[FR]: lint race condition reading BES files

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#643]
### What is the current behavior?

@gregmagolan reports a race condition between Bazel writing those report files to disk and the CLI reading them. Will need some more investigation..
fix is non-trivial so I need to block out an afternoon for it next week

### Describe the feature

the way this works under the hood is that bazel lint sets the --experimental_remote_download_regex='.*aspect_rules_lint.*' flag so that bazel downloads the results file from the remote cache if it happens to be cached. https://github.com/aspect-build/aspect-cli/blob/5e444749c7c26f6bdef9f96cd8b6ecc64a8e95b/pkg/aspect/lint/lint.go#L122

**Comment by gregmagolan** [comment]
Yes. Fixed in latest release.
