### ISSUE TITLE
[Bug]: new gitignore module causes regressions in parsing

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/aspect-cli#657]
### What happened?

There are two issues I have had since updating aspect-cli from 5.8.5 to 5.9.19

1. gitignores with `**file.txt` are noted as invalid (less of an issue)
2. gitignore with just a folder name like `generated_folder` will not be ignored by gazelle even though it is ignored by git
3. `exclude` syntax for git ignored module still causes things importing from that module to traverse the folder and generate files based on that import
4. 

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
6.4.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
Have a repo with a top level build file that sets up gazelle, but enables js generation in a subfolder only

Have a gitignore at the root of the repo and one in the subfolder. This means this gitignore extends the one above it.

Have an index file that imports from a folder that is generated by bazel via `write_source_file` which is gitignored. This provides IDE support but also generates files that are ignored by git into the source tree

Run gazelle and see the build file in the nested package update no matter what you do or where you run gazelle from
```

**Comment by jbedard** [comment]
AFAICT `**` not followed by a `/` is invalid? Try it in bash, or see the `doublestar` gomod docs as examples. But you're saying it works in a plain gitignore?

**Comment by jbedard** [comment]
> exclude syntax for git ignored module still causes things importing from that module to traverse the folder and generate files based on that import

Can you give an example of that? I'm not sure I understand the case...

**Comment by Aghassi** [comment]
> AFAICT `**` not followed by a `/` is invalid? Try it in bash, or see the `doublestar` gomod docs as examples. But you're saying it works in a plain gitignore?

It could very well be invalid syntax, but as far as I'm aware git won't throw or inform you so that _could_ be on us. For that issue, I would expect the error message be very clear. EX

```
.gitignore at path /path/to/file has the following invalid syntax:
- **thing
- etc

Please remove or fix this syntax to remove this message. This ignore will be skipped for this run
```

To the second question, the issue I was having was I had a folder named `styled-system` which was ignored in .gitignore as `styled-system`, no modifiers. Git respects the ignore and ignores it. However, gazelle does not respect the ignore and tries to add those files to the BUILD file because we had a file which imported from this folder. So what I would expect is, given an import + and ignore, the ignore takes precedence and does not add the files to the BUILD file. Does that make sense?
