### ISSUE TITLE
[FR]: [gazelle] Add `react` dependency when JSX syntax is used

### ISSUE THREAD

**Issue by walkerburgin** [aspect-build/aspect-cli#728]
### What is the current behavior?

In certain configurations, TypeScript and SWC emit `react/jsx-runtime` imports when JSX syntax is used, even when there's no explicit `react` import in the source code: 

```ts
export const Component = () => (<div>Hello, world</div>);
```

```js
import { jsx as _jsx } from "react/jsx-runtime";
export const Component = () => (_jsx("div", { children: "Hello, world" }));
```

The missing dependency causes failures downstream, e.g. when running tests. We have to manually add a `:node_modules/react,  # keep` dependency to fix the failures.

### Describe the feature

It would be awesome if the build file generator understood this behavior and automatically added the `react` dependency to the relevant `BUILD.bazel` files.

**Comment by jbedard** [comment]
I think such a feature would have to be hidden behind a flag or at least a flag to opt-out. It would also have to detect if the `react` dependency exists and where etc.

Why not just do this within a macro if your project wants it?

**Comment by walkerburgin** [comment]
> Why not just do this within a macro if your project wants it?

We can definitely work around it with a macro, but at the limit it would be nice if we didn't have to 😄. It wasn't immediately obvious that we needed to do something like this until we debugged a test failure caused by a missing dependency. I don't have a great feel for what we should want to add to Gazelle vs what we should just work around on our end yet 🤷‍♂️.

**Comment by jbedard** [comment]
Idea/proposal:

Support the tsconfig `jsx` property and declare a dependency based on that. If `"jsx": "react|react-*"` then automatically declare a `"react"` dependency that should then be resolved with normal gazelle dependency resolution.
