### ISSUE TITLE
Add aspect run

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#74]
Clearly commonly used Bazel command.

Think a bit about whether `run` already does the right thing. Like the working directory is hard to reason about right now.

Should we help the user discover `--run_under` use cases?
We could help you with the `--` in the wrong place.

multi-run is also a thing! Check what atlassian did.

**Comment by alexeagle** [comment]
multi-run is a whole project on its own, let's not accidentally build it. I'll take an AI to spec out a design doc for that eventually.

**Comment by alexeagle** [comment]
note: when my pwd is in a package with a single `*_binary` target, I clearly meant to run that

**Comment by gregmagolan** [comment]
Aspect run has been added
