### ISSUE TITLE
User settings distinct from project settings

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#75]
Viper allows us to make a second instance.

Users need their personal preferences and also check in workspace preferences.

In the MVP, let's try to make these two files totally distinct so that a given setting can only exist in one or the other.
But at some point this will probably break down and there will have to be inheritance like bazelrc

**Comment by dymart** [comment]
This has been added into the tasks for the aspect-cli config design. https://github.com/aspect-build/aspect-cli/issues/225
