### ISSUE TITLE
[Bug]: Looks like arm64 was dropped?

### ISSUE THREAD

**Issue by tradergt** [aspect-build/aspect-cli#766]
### What happened?

Release for arm64 seems to be dropped: 
```> bazel test //...
2024/10/29 13:37:16 Downloading https://github.com/aspect-build/aspect-cli/releases/download/2024.41.29/bazel-2024.41.29-linux-arm64...
2024/10/29 13:37:16 could not download Bazel: failed to download bazel: failed to download bazel: HTTP GET https://github.com/aspect-build/aspect-cli/releases/download/2024.41.29/bazel-2024.41.29-linux-arm64 failed with error 404

```

### Version

Development (host) and target OS/architectures:
Linux workstation.smelser.org 6.6.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64 GNU/Linux

Output of `bazel --version`:
> bazel --version
aspect 5.10.15

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

bazel_dep(name = "aspect_rules_py", version = "1.0.0-rc0")
bazel_dep(name = "rules_python", version = "0.37.2", dev_dependency = True)

Language(s) and/or frameworks involved:
python/go

### How to reproduce

```shell
If your on an arm64 instance, if you use the latest release, it will fail
```

**Comment by jbedard** [comment]
Yeah it looks like the binary version is different then the release version. If you use the version in the file URLs does it work for you?

I'll have to look into why the wrong filenames are being used though 🤔

**Comment by tradergt** [comment]
Its all good, I will just stay on the version I am on and get the next version or the fixed version. Mainly just wanted to report the bug.

**Comment by jbedard** [comment]
I probably would not have noticed if you didn't, thanks! 👍

**Comment by jbedard** [comment]
I think this was just me doing a release without fetching tags first, see https://github.com/aspect-build/aspect-cli/pull/767

I also kicked off a new release that should have the right numbers.

**Comment by tradergt** [comment]
Nice, I just tried it and it all works. Thanks!
