### ISSUE TITLE
[FR]: How to integrate custom test rules with configure

### ISSUE THREAD

**Issue by antspy** [aspect-build/aspect-cli#778]
### What is the current behavior?

Hi, 

I am using `rules_ts` with bazel, and by default it will create a `ts_project` rule for each `.ts` file found in a directory. The same applies to test files ending in `.spec.ts.`. 

This behavior can be modified to a limited extent using gazelle directives, but I don't see a way to get the behavior I want. 

### Describe the feature

I have a custom rule I want to use for tests. Nothing special, but it combines a `ts_project` for the test file with a `vitest` run from `load("@npm//:vitest/package_json.bzl", vitest_bin = "bin")`. 

So the idea is that I would be able to write 
```
ts_test(
    name = 'mytest', 
    srcs = ['my.test.ts'],
    deps = [...], 
)
```

and that's all. I don't see how to get the behavior I want though.

1. I cannot use a simple `aspect:map_kind` directive, because I want the substitution `ts_project` -> `ts_test` to happen only for test files, not for every filetype (other `ts` files should still use the `ts_project` rule). 
2. I looked into the [Starlark Extension API](https://docs.aspect.build/cli/starlark) (which seems really cool!) but I have found 2 issues: 
    -  The first is that the default `ts_project` behavior is not changes, so now I have both a `ts_test` rule and a `ts_project` rule, which is not what I want
    - The second is that I would have to write my own logic for `ts_test` dependencies. Here I just want to reuse the same logic from `ts_project`, just set in a different macro - but I don't want to rewrite the whole 'parse file import to add dependencies' logic. 

So my question is - what can I do about this? I am very new to this space, so perhaps there's something obvious I am missing. 
One thing that I think might work is to add a `gazelle` directive to specify which rule should be used for the `.spec.ts` targets,  so that I could set it to my own rule using the `aspect:map_kind` directive and have everything else work as it is, without having to write a custom starlark plugin

Another idea would be exporting the whole logic as a starlark extension so one could change it without having to fork / recompile the CLI, but directly adding a new plugin. 

Any help would be appreciated. Thanks a lot!

**Comment by jbedard** [comment]
Ideally all you should need is a starlark extension that generates the vitest target and takes the pre-compiled `.spec.js` files as inputs. Your vitest rule should not do anything typescript related.

See https://github.com/aspect-build/aspect-cli/issues/439 for the `map_kind` issue. I'm open to API suggestions there if you have some, and the more requests for a solution there the more likely I can put time into it 😅 

As a workaround you can do for now... use `map_kind` to use a custom `ts_project` macro, then within that macro essentially do:
```
def ts_project(name, **kwargs):
   if kwargs.get("testonly", False): # or instead match on 'name' if you have multiple testonly targets
       ts_test_project_macro(name, **kwargs)
   else:
       ts_normal_project_macro(name, **kwargs)
```

**Comment by antspy** [comment]
Hi @jbedard , 

Thanks a lot for your answer! :) 

> Ideally all you should need is a starlark extension that generates the vitest target and takes the pre-compiled .spec.js files as inputs. Your vitest rule should not do anything typescript related.

I can do this, but then I end up with two `ts_project` in my build file, which tends to confuse aspect configure. For example, this is the end state I want: 

```
ts_project(
    name = "sample",
    srcs = ["sample.ts"],
    deps = [
        "//:node_modules/@types/node"
    ],
)

ts_test(
    name = "sample_test",
    size = "small",
    srcs = ["sample.test.ts"],
    deps = [
        ":sample",
        "//:node_modules/@types/node",
    ],
)
```

and I want `aspect configure` to automatically add `ts_test` targets when they are missing, and update the `deps` automatically. The `ts_test` macro generates an internal `ts_project` and has a `vitest_test` target which depends on the internal `ts_project` rule. 

Following your suggestion, I could add a custom plugin that only generates the `vitest_test` target, and leave the automatic `ts_project` alone, resulting in something like this: 

```
ts_project(
    name = "sample",
    srcs = ["sample.ts"],
    deps = [
        "//:node_modules/@types/node"
    ],
)

# gazelle:js_project_naming_convention sample_test_lib
ts_project(
    name = "sample_test_lib",
    srcs = ["sample.test.ts"],
    deps = [
        "//:node_modules/@types/node"
    ],
)

vitest(
    name = "sample_test",
    size = "small",
    srcs = ["sample.test.ts"],
    data = [
        ":sample_test_lib",
    ],
)
```

But this doesn't seem a great solution, because 
1. `aspect configure` by default expects a single `ts_project` per directory, so I need to add manually the directive ` # gazelle:js_project_naming_convention sample_test_lib` to avoid configure complaining that the target already exists. 
2. If I import the `sample` library in other files, `configure` gets confused that there is more than one `ts_project` in the build. I get errors like " “Import “../../sample.js” from “xxx” resolved to multiple targets (//…:sample, //…:sample_lib_test)”". So how would I disambiguate between the two? 
3. Having an extra ts_project adds boilerplate for no reason. Ideally we would have something like in python - there is a `py_library`, a `py_binary`, and a `py_test`. The less boilerplate we have in `BUILD` files the better. 

Please let me know what you think! :) 

> See https://github.com/aspect-build/aspect-cli/issues/439 for the map_kind issue. I'm open to API suggestions there if you have some

yes that's exactly what I want :) I agree with the suggestion in the FR, you can add a different `kind` generated for `.spec.ts` files, which then would allow us to use `map_kind` and use our custom macros. This seems relatively low effort to support and would allow us to have our own macros used for testing, which is pretty cool. 

Perhaps the best solution long term is to move away from pre-compiled binaries (removing the `go` lib entirely) but provide libraries for custom plugins to configure (https://docs.aspect.build/cli/starlark) - so one can have full control over the generated targets. 

Because essentially, the real hard things that `configure` does is automatically adding the dependency. Then all the rest of it (naming, auto-creating the targets, etc.) is sort of useful but not that big of a deal - you can get by very easily just copy pasting.[0]  It's dependencies which are a pain and need `configure` to be updated. So just adding a starlark library that takes in input a file and returns a list of dependencies would be great, and then one can easily configure naming and target type generation just by changing the `declare_targets` function. 


[0] In fact, I find `configure` to be too opinionated in the naming of the targets. I would argue that if I target already exists, it should not rename it or try to add extra targets. If I could only enable `configure` as a way to add dependencies and nothing else (`build_cleaner` style), I would - I don't really need automatic target generations.

**Comment by jbedard** [comment]
> 1. aspect `configure` by default expects a single ts_project per directory, so I need to add manually the directive  # gazelle:js_project_naming_convention sample_test_lib to avoid configure complaining that the target already exists.

By default it actually has 2 `ts_project`s per directory: lib + tests. You can override the default names and globs for those targets, you can also add custom targets (such as e2e tests etc) with additional names + globs.

> 2. If I import the sample library in other files, configure gets confused that there is more than one ts_project in the build. I get errors like " “Import “../../sample.js” from “xxx” resolved to multiple targets (//…:sample, //…:sample_lib_test)”". So how would I disambiguate between the two?

A source file should only be in one `ts_project` target, otherwise it makes sense that it can't resolve to a single target.

> 3. Having an extra ts_project adds boilerplate for no reason. Ideally we would have something like in python - there is a py_library, a py_binary, and a py_test. The less boilerplate we have in BUILD files the better.

What do you consider to be "extra"? Each `.ts` should be in a single `ts_project`. If you're writing non-generated `ts_project`s then those sources should be excluded from the generated ones, but I'd hope you don't need anything non-generated.

> [0] In fact, I find configure to be too opinionated in the naming of the targets. I would argue that if I target already exists, it should not rename it or try to add extra targets. If I could only enable configure as a way to add dependencies and nothing else (build_cleaner style), I would - I don't really need automatic target generations.

You can name the targets whatever you want and provide whatever source globs you want, see https://docs.aspect.build/cli/help/directives/#javascript

While configure can understand the outputs of any target, it can only generate attributes for targets it generates. So unfortunately if you want `ts_project(deps)` generated then the full `ts_project` needs to be generated.

> This seems relatively low effort to support and would allow us to have our own macros used for testing, which is pretty cool.

I haven't looked at this in a long time but from what I can recall it wasn't that easy because `map_kind` is implemented within the gazelle core and was awkward to customize or patch. I think short term it would be easier for you to detect lib vs tests by name like I suggested, but ideally you wouldn't have to do this at all.

**Comment by antspy** [comment]
Thank you for your answer!! :) 

> By default it actually has 2 ts_projects per directory: lib + tests. You can override the default names and globs for those targets, you can also add custom targets (such as e2e tests etc) with additional names + globs.

Do you have pointers on how to do this? I have read https://docs.aspect.build/cli/help/directives/#javascript but I don't see the options you refer to. The `# gazelle:js_project_naming_convention` only documents the `{dirname}` attribute - I tried changing it to `{filename}`, but it did not seem to work. I can make it work if I add them to every `BUILD` file, but not as a global option in the root `BUILD` file. 

> A source file should only be in one ts_project target, otherwise it makes sense that it can't resolve to a single target.

It is - and gazelle is still confused. As you can see in my previous comment, the `"sample.ts"` file is in a single `ts_project` (as source), and configure still cannot disambiguate. It's possible I am doing something obviously wrong - is the following not a standard configuration? How would you improve it? 

```
ts_project(
    name = "sample",
    srcs = ["sample.ts"],
    deps = [
        "//:node_modules/@types/node"
    ],
)

# gazelle:js_project_naming_convention sample_test_lib
ts_project(
    name = "sample_test_lib",
    srcs = ["sample.test.ts"],
    deps = [
        "//:node_modules/@types/node"
    ],
)

vitest(
    name = "sample_test",
    size = "small",
    srcs = ["sample.test.ts"],
    data = [
        ":sample_test_lib",
    ],
)
```

> What do you consider to be "extra"? Each .ts should be in a single ts_project.

The `ts_project` for the test is 'extra', because I don't need to rely on this in other libraries - it's just there so I can run `bazel test`. So in this case I want to ensure the test itself is there (`sample_test`) but the `sample_test_lib` (in the code above) is superfluous, and it's only there to make `configure` happy. Does this make sense? 

>  I think short term it would be easier for you to detect lib vs tests by name like I suggested, but ideally you wouldn't have to do this at all.

I see - this makes sense, if I can get `configure` to not complain about having conflicts between the `sample` project and the `sample_test_lib` project, this will work fine for me! :) 

Again, thanks for all the support!

**Comment by jbedard** [comment]
> Do you have pointers on how to do this? 

The `js_files` and `js_test_files` can be used to customize the globs, but I don't think you should even need that if you do what I'm suggesting.

> The ts_project for the test is 'extra', because I don't need to rely on this in other libraries - it's just there so I can run bazel test. So in this case I want to ensure the test itself is there (sample_test) but the sample_test_lib (in the code above) is superfluous, and it's only there to make configure happy. Does this make sense?

Other libraries don't need that `ts_project` but your tests do. Your test runner should run tests, not compile typescript code. If you want you can add a `visibility` attribute to ensure nothing else depends on the test `ts_project`, or doing that automatically could be a reasonable feature request.

I think the only code you should write (or generate with a starlark plugin!) would be:
```
vitest(
    name = "sample_test",
    size = "small",
    srcs = ["sample.test.js"],
    data = [
        ":sample_test_lib",
    ],
)
```
Note the `srcs` includes the pre-compiled `.js`, not the `.ts`. The 2 `ts_project` targets should be fully generated with `configure`.

**Comment by antspy** [comment]
Ok thank you - I gave up on trying to customize the ts_projects then (I wanted to allow more than one ts_project per directory) but that looks like it's asking for trouble. 

For posterity: 
I have added the following directive to the root build file 
`# gazelle:js_tests_naming_convention {dirname}_test_lib`

and created a custom starlark plugin that adds the `vitest` rule whenever a `xx.test.ts` file is encountered. This test rule depends on the `{dirname}_test_lib` project (generated by the standard `bazel configure`). 

Thank you for all the help! That's very appreciated :)

**Comment by jbedard** [comment]
> I gave up on trying to customize the ts_projects then (I wanted to allow more than one ts_project per directory) but that looks like it's asking for trouble.

You should have 2 `ts_project`s per directory by default: lib + tests. Is that not what you're seeing?

> and created a custom starlark plugin that adds the vitest rule whenever a xx.test.ts file is encountered. This test rule depends on the {dirname}_test_lib project (generated by the standard bazel configure).

Awesome. Any feedback or suggestions for the starlark API would be great 👍

**Comment by antspy** [comment]
> You should have 2 ts_projects per directory by default: lib + tests. Is that not what you're seeing?

yes, thank you! But I don't like the idea of having a single ts_project (plus the test) for directory. I would like to be able to have e.g. 5 files in a directory, each file in a different ts_project (similarly to what I do with python - every python file is a py_library, and how many are in a directory is not important). 

Anyway, since this confused bazel configure and seems to not be well supported, I will drop the idea. 
Thanks! 


> Any feedback or suggestions for the starlark API would be great 

I really like the plugin extensions so far. I think the only thing you're really missing is providing libraries for the 'hard jobs', which are the 'fixing dependencies' stuff. If we could call a function that takes a file in input and returns a list of dependencies for the `ts_project` / `py_library` etc, that would be super useful. 

This would mean we can fully customize the ts_project structure just by writing some simple regexp and logic in the starlark file, and calling the lib function for the heavy lifting of analysing those files and adding the right dependencies. Right now you have the logic embedded in the `go` binary, would be cool to fully port it and make it available to the starlark API :)

**Comment by jbedard** [comment]
> I would like to be able to have e.g. 5 files in a directory, each file in a different ts_project

I've never seen anyone do that before. Is the intention to have 5 separate `tsc` invocations? Or 5 separate bazel test targets? (or both)

**Comment by jbedard** [comment]
> Right now you have the logic embedded in the go binary, would be cool to fully port it and make it available to the starlark API

You have custom logic in go that the js language (in aspect-cli) then picks up? What type of logic would that be and how does it effect a different gazelle language?

**Comment by antspy** [comment]
> I've never seen anyone do that before. Is the intention to have 5 separate tsc invocations? Or 5 separate bazel test targets? (or both)

The intention is to be able to distnguish between libraries & folders. To make a python example - I might have 20 files in a directory (e.g. `utils`) and have each file be its own library, which is compiled and included only when needed. 

In typescript, I have to either 
1. Create 20 different folders, which is not what I want 
2. Have a single ts project containing 20 files. Now all 20 files are compiled & included even when I use only one of them, since they are all part of the same ts_project. 

> You have custom logic in go that the js language (in aspect-cli) then picks up? What type of logic would that be and how does it effect a different gazelle language?

My idea was that instead of providing some custom gazelle directives for js (like you do in https://docs.aspect.build/cli/help/directives/#javascript) which can be used to customize only a small part of the generation logic, you could allow people to use whatever logic they want (in terms of organization of BUILD files, ts projects, etc.) by allowing them to write their own starlark plugin with whatever logic they want. 

This is already possible now, but the problem is that the 'add dependency' logic cannot be replicated in the plugin system, unless you write it yourself. If there was a way to just call `list_dependencies(file)` from the starlak plugin, then writing such a plugin would be super easy.

**Comment by jbedard** [comment]
I have never seen ts files individually compiled like that, only ever in groups such as library+tests and often additional groups such as "e2e tests", "storybook", "mocks" etc.

Note that when using a `ts_project(transpiler)` the files can still be individually compiled+cached (for example with rules_swc). It will still be one target with one `ts_project(deps)` so that doesn't do exactly what you're looking for, but does avoid running tsc on everything when you simply need a single .ts re-transpiled to .js such as running a test.

I'll have to think about the `list_dependencies(file)` thing but I can't promise anything. I think the existing js plugin fulfills the standard requirements and additional starlark plugins should depend on that instead of trying to re-implement it.

**Comment by antspy** [comment]
Thanks a lot for your answers, they are much appreciated!! :) 

I think the current solution of having one ts_project per dir, + one ts_project for the test, + one vitest target (added with a custom starlark plugin) is good enough :) I guess I am too used to python's setup of having one py_library per file, and perhaps this is not the way to go with typescript. 

Regardless, thank you for the support! :)
