### ISSUE TITLE
[Bug]: `bazel configure` adds generated files to `ts_project()` `deps`

### ISSUE THREAD

**Issue by walkerburgin** [aspect-build/aspect-cli#782]
### What happened?

Running `bazel configure` adds generated files to `ts_project()`'s `deps`, which then fails to compile with an error like this: 

```
ERROR: /Users/walkerburgin/Repositories/walkerburgin/configure-genrule-repro/pkgs/foo-lib/BUILD.bazel:19:11: in deps attribute of ts_project rule //pkgs/foo-lib:typescript: generated file '//pkgs/foo-lib:r1.ts' is misplaced here (expected no files). Since this rule was created by the macro 'ts_project', the error might have been caused by the macro implementation
ERROR: /Users/walkerburgin/Repositories/walkerburgin/configure-genrule-repro/pkgs/foo-lib/BUILD.bazel:19:11: in deps attribute of ts_project rule //pkgs/foo-lib:typescript: generated file '//pkgs/foo-lib:r2.d.ts' is misplaced here (expected no files). Since this rule was created by the macro 'ts_project', the error might have been caused by the macro implementation
ERROR: /Users/walkerburgin/Repositories/walkerburgin/configure-genrule-repro/pkgs/foo-lib/BUILD.bazel:19:11: Analysis of target '//pkgs/foo-lib:typescript' failed
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `aspect 2024.46.33-399d18a70`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

```
bazel_dep(name = "aspect_rules_js", version = "2.1.1")
bazel_dep(name = "aspect_rules_ts", version = "3.3.1")
```

Language(s) and/or frameworks involved: TypeScript

### How to reproduce

- Clone https://github.com/walkerburgin/configure-genrule-repro (adapted from [`gazelle/js/tests/simple_import_generated`](https://github.com/aspect-build/aspect-cli/tree/848653ce3783885bcf30b2c8726bbe3ca90c2caa/gazelle/js/tests/simple_import_generated))
- Run `bazel configure` 
- Run `bazel build //...`

**Comment by jbedard** [comment]
Hmm, I don't recall why it was done this way, and it seems wrong as you're pointing out.

In your use case what would the desired behaviour be? I think the generated files would go into the `ts_project(srcs)` if they match the glob for that `ts_project`, just as if those generated files were in the source tree. Would that work in your scenario? Or maybe your scenario they wouldn't match any glob and not be added to any `srcs`?

**Comment by walkerburgin** [comment]
Together with https://github.com/aspect-build/aspect-cli/issues/783 my goal is to do something similar to what is described [here](https://www.typescriptlang.org/tsconfig/#rootDirs) and do TypeScript code-generation on CSS modules using [this](https://github.com/styu/postcss-typesafe-css-modules) to type check CSS module imports. I think that means I'd want the generated files to go into `ts_project(srcs)`.
