### ISSUE TITLE
[FR]: Add support to `configure` for generated files in `rootDirs`

### ISSUE THREAD

**Issue by walkerburgin** [aspect-build/aspect-cli#783]
### What is the current behavior?

- `bazel configure` supports adding dependencies on generated files
- `bazel configure` supports adding dependencies based on `tsconfig`'s `rootDirs`
- `bazel configure` does not support adding dependencies on generated files in `rootDirs`. 

### Describe the feature

It would be great for `bazel configure` to add dependencies on generated files located in `rootDirs` directories. My understanding is that this is one of the primary use cases for `rootDirs` (as mentioned in the [docs](https://www.typescriptlang.org/tsconfig/#rootDirs)). I put together a standalone repro [here](https://github.com/walkerburgin/configure-genrule-rootdirs-repro )

**Comment by jbedard** [comment]
FYI I believe this was fixed in the same change as the fix for https://github.com/aspect-build/aspect-cli/issues/782

I'll add a test to verify and then hopefully publish a new cli release and push the changes to this repo this week

**Comment by walkerburgin** [comment]
Awesome, thank you!
